### ISSUE TITLE
Swift 5 compatability

### ISSUE THREAD

**Issue by lonkly** [MostafaTaghipour/mtpThemeManager#1]
Using mtpThemeManager with Swift 5 does not compile:
`  allClasses.deallocate(capacity: Int(expectedClassCount))`
 with error:
`Pods/mtpThemeManager/mtpThemeManager/Classes/ThemeManager.swift:159:20: 'deallocate(capacity:)' is unavailable: Swift currently only supports freeing entire heap blocks, use deallocate() instead`

**Comment by MostafaTaghipour** [comment]
Thank you @lonkly , I will fix the problem as soon as possible and publish the corrected code

**Comment by MostafaTaghipour** [comment]
mtpThemeManager updated, It's now compatible with swift 5
